// Per-character lookup tables for kana shape manipulation. Inverting these in code is brittle
// (the easy regex turns ぱ into both は and ば), so we keep the canonical mapping explicit and
// derive the inverse where needed.

// Voiced (dakuten) → unvoiced base character. Used by `stripDakuten` to detect dakuten errors:
// `がくせい` vs `かくせい` differ only by dakuten.
export const DAKUTEN_TO_BASE: Readonly<Record<string, string>> = {
  // hiragana
  が: 'か',
  ぎ: 'き',
  ぐ: 'く',
  げ: 'け',
  ご: 'こ',
  ざ: 'さ',
  じ: 'し',
  ず: 'す',
  ぜ: 'せ',
  ぞ: 'そ',
  だ: 'た',
  ぢ: 'ち',
  づ: 'つ',
  で: 'て',
  ど: 'と',
  ば: 'は',
  び: 'ひ',
  ぶ: 'ふ',
  べ: 'へ',
  ぼ: 'ほ',
  // katakana
  ガ: 'カ',
  ギ: 'キ',
  グ: 'ク',
  ゲ: 'ケ',
  ゴ: 'コ',
  ザ: 'サ',
  ジ: 'シ',
  ズ: 'ス',
  ゼ: 'セ',
  ゾ: 'ソ',
  ダ: 'タ',
  ヂ: 'チ',
  ヅ: 'ツ',
  デ: 'テ',
  ド: 'ト',
  バ: 'ハ',
  ビ: 'ヒ',
  ブ: 'フ',
  ベ: 'ヘ',
  ボ: 'ホ',
  ヴ: 'ウ',
};

// Half-voiced (handakuten) → unvoiced base. Pairs: ぱ/は, ぴ/ひ, etc.
export const HANDAKUTEN_TO_BASE: Readonly<Record<string, string>> = {
  ぱ: 'は',
  ぴ: 'ひ',
  ぷ: 'ふ',
  ぺ: 'へ',
  ぽ: 'ほ',
  パ: 'ハ',
  ピ: 'ヒ',
  プ: 'フ',
  ペ: 'ヘ',
  ポ: 'ホ',
};

// Small youon kana → its full-size form. しゃ vs しや differ here.
export const YOUON_SMALL_TO_BIG: Readonly<Record<string, string>> = {
  ゃ: 'や',
  ゅ: 'ゆ',
  ょ: 'よ',
  ャ: 'ヤ',
  ュ: 'ユ',
  ョ: 'ヨ',
  // small a/i/u/e/o (ぁぃぅぇぉ) appear in modern loanwords like ティー — normalise them too.
  ぁ: 'あ',
  ぃ: 'い',
  ぅ: 'う',
  ぇ: 'え',
  ぉ: 'お',
  ァ: 'ア',
  ィ: 'イ',
  ゥ: 'ウ',
  ェ: 'エ',
  ォ: 'オ',
};

// Sokuon: small tsu in both scripts.
export const SOKUON_CHARS: ReadonlySet<string> = new Set(['っ', 'ッ']);

// Long-vowel marks. ー is the canonical katakana mark; we treat it strictly here.
export const LONG_VOWEL_MARK = 'ー';

// Vowel of each kana (used to expand ー into the corresponding double vowel).
// Empty string means the kana is voicing-only or invalid as a long-vowel anchor (sokuon, ん).
export const KANA_TO_VOWEL: Readonly<Record<string, '' | 'a' | 'i' | 'u' | 'e' | 'o'>> = {
  // a-row
  あ: 'a',
  か: 'a',
  さ: 'a',
  た: 'a',
  な: 'a',
  は: 'a',
  ま: 'a',
  や: 'a',
  ら: 'a',
  わ: 'a',
  が: 'a',
  ざ: 'a',
  だ: 'a',
  ば: 'a',
  ぱ: 'a',
  きゃ: 'a',
  しゃ: 'a',
  ちゃ: 'a',
  にゃ: 'a',
  ひゃ: 'a',
  みゃ: 'a',
  りゃ: 'a',
  ぎゃ: 'a',
  じゃ: 'a',
  びゃ: 'a',
  ぴゃ: 'a',
  ア: 'a',
  カ: 'a',
  サ: 'a',
  タ: 'a',
  ナ: 'a',
  ハ: 'a',
  マ: 'a',
  ヤ: 'a',
  ラ: 'a',
  ワ: 'a',
  ガ: 'a',
  ザ: 'a',
  ダ: 'a',
  バ: 'a',
  パ: 'a',
  // i-row
  い: 'i',
  き: 'i',
  し: 'i',
  ち: 'i',
  に: 'i',
  ひ: 'i',
  み: 'i',
  り: 'i',
  ぎ: 'i',
  じ: 'i',
  ぢ: 'i',
  び: 'i',
  ぴ: 'i',
  イ: 'i',
  キ: 'i',
  シ: 'i',
  チ: 'i',
  ニ: 'i',
  ヒ: 'i',
  ミ: 'i',
  リ: 'i',
  ギ: 'i',
  ジ: 'i',
  ヂ: 'i',
  ビ: 'i',
  ピ: 'i',
  // u-row
  う: 'u',
  く: 'u',
  す: 'u',
  つ: 'u',
  ぬ: 'u',
  ふ: 'u',
  む: 'u',
  ゆ: 'u',
  る: 'u',
  ぐ: 'u',
  ず: 'u',
  づ: 'u',
  ぶ: 'u',
  ぷ: 'u',
  きゅ: 'u',
  しゅ: 'u',
  ちゅ: 'u',
  にゅ: 'u',
  ひゅ: 'u',
  みゅ: 'u',
  りゅ: 'u',
  ぎゅ: 'u',
  じゅ: 'u',
  びゅ: 'u',
  ぴゅ: 'u',
  ヴ: 'u',
  ウ: 'u',
  ク: 'u',
  ス: 'u',
  ツ: 'u',
  ヌ: 'u',
  フ: 'u',
  ム: 'u',
  ユ: 'u',
  ル: 'u',
  グ: 'u',
  ズ: 'u',
  ヅ: 'u',
  ブ: 'u',
  プ: 'u',
  // e-row
  え: 'e',
  け: 'e',
  せ: 'e',
  て: 'e',
  ね: 'e',
  へ: 'e',
  め: 'e',
  れ: 'e',
  げ: 'e',
  ぜ: 'e',
  で: 'e',
  べ: 'e',
  ぺ: 'e',
  エ: 'e',
  ケ: 'e',
  セ: 'e',
  テ: 'e',
  ネ: 'e',
  ヘ: 'e',
  メ: 'e',
  レ: 'e',
  ゲ: 'e',
  ゼ: 'e',
  デ: 'e',
  ベ: 'e',
  ペ: 'e',
  // o-row
  お: 'o',
  こ: 'o',
  そ: 'o',
  と: 'o',
  の: 'o',
  ほ: 'o',
  も: 'o',
  よ: 'o',
  ろ: 'o',
  を: 'o',
  ご: 'o',
  ぞ: 'o',
  ど: 'o',
  ぼ: 'o',
  ぽ: 'o',
  きょ: 'o',
  しょ: 'o',
  ちょ: 'o',
  にょ: 'o',
  ひょ: 'o',
  みょ: 'o',
  りょ: 'o',
  ぎょ: 'o',
  じょ: 'o',
  びょ: 'o',
  ぴょ: 'o',
  オ: 'o',
  コ: 'o',
  ソ: 'o',
  ト: 'o',
  ノ: 'o',
  ホ: 'o',
  モ: 'o',
  ヨ: 'o',
  ロ: 'o',
  ヲ: 'o',
  ゴ: 'o',
  ゾ: 'o',
  ド: 'o',
  ボ: 'o',
  ポ: 'o',
};

// Hiragana vowel kana, indexed by short vowel letter.
export const VOWEL_TO_HIRAGANA: Readonly<Record<'a' | 'i' | 'u' | 'e' | 'o', string>> = {
  a: 'あ',
  i: 'い',
  u: 'う',
  e: 'え',
  o: 'お',
};

export const VOWEL_TO_KATAKANA: Readonly<Record<'a' | 'i' | 'u' | 'e' | 'o', string>> = {
  a: 'ア',
  i: 'イ',
  u: 'ウ',
  e: 'エ',
  o: 'オ',
};

// Helper: get the vowel of the kana char preceding position `i` in `s`. Returns empty when the
// preceding char is sokuon, ん, or non-kana.
export function vowelOfPrev(s: string, i: number): '' | 'a' | 'i' | 'u' | 'e' | 'o' {
  if (i <= 0) return '';
  const prev = s[i - 1];
  if (!prev) return '';
  return KANA_TO_VOWEL[prev] ?? '';
}

// Hiragana / katakana / iteration / long-vowel range. Used by `isAllKana` etc.
export const KANA_REGEX = /^[぀-ゟ゠-ヿーゝゞヽヾ]+$/u;

export function isAllKana(s: string): boolean {
  return KANA_REGEX.test(s);
}
